// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(BasicBillingContext))]
    partial class BasicBillingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Domain.Entities.Billing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillingCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillingStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Charge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BillingCategoryId");

                    b.HasIndex("BillingStatusId");

                    b.HasIndex("ClientId");

                    b.ToTable("Billings");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            BillingCategoryId = 1,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 100,
                            Period = 202001
                        },
                        new
                        {
                            Id = 101,
                            BillingCategoryId = 1,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 100,
                            Period = 202002
                        },
                        new
                        {
                            Id = 102,
                            BillingCategoryId = 1,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 200,
                            Period = 202001
                        },
                        new
                        {
                            Id = 103,
                            BillingCategoryId = 1,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 200,
                            Period = 202002
                        },
                        new
                        {
                            Id = 104,
                            BillingCategoryId = 1,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 300,
                            Period = 202001
                        },
                        new
                        {
                            Id = 105,
                            BillingCategoryId = 1,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 300,
                            Period = 202002
                        },
                        new
                        {
                            Id = 106,
                            BillingCategoryId = 1,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 400,
                            Period = 202001
                        },
                        new
                        {
                            Id = 107,
                            BillingCategoryId = 1,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 400,
                            Period = 202002
                        },
                        new
                        {
                            Id = 108,
                            BillingCategoryId = 1,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 500,
                            Period = 202001
                        },
                        new
                        {
                            Id = 109,
                            BillingCategoryId = 1,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 500,
                            Period = 202002
                        },
                        new
                        {
                            Id = 110,
                            BillingCategoryId = 2,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 100,
                            Period = 202001
                        },
                        new
                        {
                            Id = 111,
                            BillingCategoryId = 2,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 100,
                            Period = 202002
                        },
                        new
                        {
                            Id = 112,
                            BillingCategoryId = 2,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 200,
                            Period = 202001
                        },
                        new
                        {
                            Id = 113,
                            BillingCategoryId = 2,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 200,
                            Period = 202002
                        },
                        new
                        {
                            Id = 114,
                            BillingCategoryId = 2,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 300,
                            Period = 202001
                        },
                        new
                        {
                            Id = 115,
                            BillingCategoryId = 2,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 300,
                            Period = 202002
                        },
                        new
                        {
                            Id = 116,
                            BillingCategoryId = 2,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 400,
                            Period = 202001
                        },
                        new
                        {
                            Id = 117,
                            BillingCategoryId = 2,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 400,
                            Period = 202002
                        },
                        new
                        {
                            Id = 118,
                            BillingCategoryId = 2,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 500,
                            Period = 202001
                        },
                        new
                        {
                            Id = 119,
                            BillingCategoryId = 2,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 500,
                            Period = 202002
                        },
                        new
                        {
                            Id = 120,
                            BillingCategoryId = 3,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 100,
                            Period = 202001
                        },
                        new
                        {
                            Id = 121,
                            BillingCategoryId = 3,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 100,
                            Period = 202002
                        },
                        new
                        {
                            Id = 122,
                            BillingCategoryId = 3,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 200,
                            Period = 202001
                        },
                        new
                        {
                            Id = 123,
                            BillingCategoryId = 3,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 200,
                            Period = 202002
                        },
                        new
                        {
                            Id = 124,
                            BillingCategoryId = 3,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 300,
                            Period = 202001
                        },
                        new
                        {
                            Id = 125,
                            BillingCategoryId = 3,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 300,
                            Period = 202002
                        },
                        new
                        {
                            Id = 126,
                            BillingCategoryId = 3,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 400,
                            Period = 202001
                        },
                        new
                        {
                            Id = 127,
                            BillingCategoryId = 3,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 400,
                            Period = 202002
                        },
                        new
                        {
                            Id = 128,
                            BillingCategoryId = 3,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 500,
                            Period = 202001
                        },
                        new
                        {
                            Id = 129,
                            BillingCategoryId = 3,
                            BillingStatusId = 1,
                            Charge = "200",
                            ClientId = 500,
                            Period = 202002
                        });
                });

            modelBuilder.Entity("Domain.Entities.BillingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BillingCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "WATER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ELECTRICITY"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SEWER"
                        });
                });

            modelBuilder.Entity("Domain.Entities.BillingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BillingStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Paid"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Name = "Joseph Carlton"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Maria Juarez"
                        },
                        new
                        {
                            Id = 300,
                            Name = "Albert Kenny"
                        },
                        new
                        {
                            Id = 400,
                            Name = "Jessica Phillips"
                        },
                        new
                        {
                            Id = 500,
                            Name = "Charles Johnson"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Billing", b =>
                {
                    b.HasOne("Domain.Entities.BillingCategory", "BillingCategory")
                        .WithMany("Billings")
                        .HasForeignKey("BillingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.BillingStatus", "BillingStatus")
                        .WithMany("Billings")
                        .HasForeignKey("BillingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingCategory");

                    b.Navigation("BillingStatus");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.Entities.BillingCategory", b =>
                {
                    b.Navigation("Billings");
                });

            modelBuilder.Entity("Domain.Entities.BillingStatus", b =>
                {
                    b.Navigation("Billings");
                });
#pragma warning restore 612, 618
        }
    }
}
